### PR TITLE
Curricular model template - resolves #1

### LINKED ISSUE #1: Curricular Model Submission Template
Need to develop a template for submissions of curricular models.

### PR DESCRIPTION
**Pull request by ProfJanetDavis**
Here is the first fleshed out draft of a curricular model template. I am working in parallel on applying the template to describe our curriculum at Whitman. That's still work in progress, but I thought I would go ahead and request feedback on the template itself.

### CODE REVIEW

**Comment by ProfJanetDavis** [comment]
@braughtg, can you explain why you want each submission to have its own directory, rather than a single Markdown file?

**Comment by braughtg** [comment]
> @braughtg, can you explain why you want each submission to have its own directory, rather than a single Markdown file?

@ProfJanetDavis I had imagined that some submissions might want to include a figure or image.  In particular for the Dickinson model I might include the diagram of our major

Dickinson CS Major

Being able to include the file in the repo rather than just linking will provide a more permanent resource.

**Comment by braughtg** [comment]
@ProfJanetDavis  do you want to merge this PR now or wait until you've completed a draft of the Whitman model to be sure it works as intended?

**Review by braughtg — APPROVED** [review]
This looks good.  I will have a go at writing one for Dickinson hopefully later this week.

**Comment by ProfJanetDavis** [comment]
Your reason makes sense! I'll move my draft for Whitman into a directory and add a little more instruction to the call. I'll merge my PR when the draft is complete.

**Pull request merged**
